// Weekly task board — a simple day-by-day checklist (Mon-Sun, real dates),
// persisted the same way as everything else (IndexedDB, no server). Not
// tied to leads/scanning at all — see CLAUDE.md.
//
// contactId/priority (below) are an additive extension, per Jack: "so sales
// reps know which contacts are the most important" — a task can optionally
// point at a Contact and carry an urgency level, created from the Contacts
// page (see lib/contacts.ts, components/Contacts.tsx). Both fields are
// optional so every existing plain Board task (created via createTask, with
// neither field) keeps working exactly as before — the Board itself renders
// a contact-linked task exactly like any other, since its readable `text`
// already has the contact's name baked in at creation time (see
// createContactTask below); nothing about Board's own rendering changed.
import { dbGetAll, dbPut, dbDelete, STORE_TASKS } from "./db";

export type TaskPriority = "high" | "medium" | "low";

export interface Task {
  id: string;
  date: string; // YYYY-MM-DD, the specific calendar day this task belongs to
  text: string;
  done: boolean;
  createdAt: string;
  // Set only for a task created from the Contacts page — which specific
  // Contact this follow-up is about, and how urgent it is. Absent/null on
  // every ordinary Board task.
  contactId?: string | null;
  priority?: TaskPriority | null;
  // The outbound channel this task is — call or email — so it can be
  // worked from its own dedicated queue (Engage's Calls/Emails tabs) as
  // well as the general Board. Absent/null = an ordinary task, same as
  // every task before this field existed. First native slice of "start
  // building out sequence and actual tasks slowly" (see CLAUDE.md) —
  // deliberately reuses this same Task store rather than a new one, same
  // as contactId/priority above.
  channel?: "call" | "email" | null;
  // Set only for a task generated by a Sequence enrollment's current step
  // (see lib/sequences.ts) — links this task back to the enrollment so
  // completing it (onToggleTask) can advance the enrollment to its next
  // step. Absent/null = an ordinary task (including plain Calls/Emails
  // tasks created by hand), completely unaffected.
  sequenceEnrollmentId?: string | null;
  // Optional time of day for this task, "HH:MM" (24h). Per Jack, follow-ups
  // on the Home dashboard should show "with the time" — but every task
  // before this field existed (and every task created without picking a
  // time) is still a plain calendar-day task, so this is strictly optional
  // and additive, exactly like contactId/priority/channel above. Nothing
  // reads it except display/sorting; `date` remains the only scheduling key.
  time?: string | null;
}

function newId() {
  return `task-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
}

export async function loadTasksFromDB(): Promise<Task[]> {
  return dbGetAll<Task>(STORE_TASKS);
}
export async function persistTask(task: Task) {
  await dbPut(STORE_TASKS, task);
}
export async function deleteTaskFromDB(id: string) {
  await dbDelete(STORE_TASKS, id);
}

export function createTask(date: string, text: string): Task | null {
  const trimmed = text.trim();
  if (!trimmed) return null;
  return { id: newId(), date, text: trimmed, done: false, createdAt: new Date().toISOString() };
}

export function createContactTask(
  date: string,
  text: string,
  contactId: string,
  priority: TaskPriority,
  channel?: "call" | "email",
  time?: string | null
): Task | null {
  const base = createTask(date, text);
  if (!base) return null;
  return { ...base, contactId, priority, channel: channel ?? null, time: time || null };
}

// A task generated by a Sequence enrollment's current step — see
// lib/sequences.ts. Same shape as a contact task, plus the enrollment
// back-link that lets completing this task advance the enrollment.
export function createSequenceTask(
  date: string,
  text: string,
  contactId: string,
  channel: "call" | "email" | "linkedin",
  sequenceEnrollmentId: string,
  priority: TaskPriority = "medium"
): Task | null {
  const base = createTask(date, text);
  if (!base) return null;
  // LinkedIn steps ride the Task store's existing "call"|"email" channel
  // typing for the Calls/Emails tabs — a LinkedIn step's task shows up in
  // the sequence's own enrollment view (not a third channel tab, since
  // that pairing wasn't asked for) but not Calls/Emails, so it's tagged
  // null there rather than forced into an unrelated channel.
  return { ...base, contactId, priority, channel: channel === "linkedin" ? null : channel, sequenceEnrollmentId };
}

function dateKey(d: Date): string {
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, "0");
  const day = String(d.getDate()).padStart(2, "0");
  return `${y}-${m}-${day}`;
}

// Monday-start week, matching lib/history.ts's week convention.
export function startOfWeek(d: Date): Date {
  const date = new Date(d);
  const day = date.getDay();
  const diff = day === 0 ? -6 : 1 - day;
  date.setHours(0, 0, 0, 0);
  date.setDate(date.getDate() + diff);
  return date;
}

export interface DayColumn {
  key: string; // YYYY-MM-DD
  date: Date;
  label: string; // e.g. "Mon, Aug 24"
}

export function getWeekDays(weekStart: Date): DayColumn[] {
  return Array.from({ length: 7 }, (_, i) => {
    const d = new Date(weekStart);
    d.setDate(d.getDate() + i);
    return {
      key: dateKey(d),
      date: d,
      label: d.toLocaleDateString(undefined, { weekday: "short", month: "short", day: "numeric" }),
    };
  });
}

export function weekRangeLabel(weekStart: Date): string {
  const end = new Date(weekStart);
  end.setDate(end.getDate() + 6);
  const fmt = (d: Date) => d.toLocaleDateString(undefined, { month: "short", day: "numeric" });
  const sameYear = weekStart.getFullYear() === end.getFullYear();
  return `${fmt(weekStart)} – ${fmt(end)}${sameYear ? `, ${end.getFullYear()}` : ""}`;
}

// Today's calendar day, in the same YYYY-MM-DD shape Task.date uses.
// Several components computed this inline already — exported here so the
// Home dashboard and everything else agree on what "today" means.
export function todayDateKey(): string {
  return dateKey(new Date());
}

// "14:30" -> "2:30 PM" (locale-formatted). Returns "" for an untimed task,
// so a caller can render an "anytime today" fallback instead.
export function formatTaskTime(time?: string | null): string {
  if (!time) return "";
  const [h, m] = time.split(":").map(Number);
  if (!Number.isFinite(h) || !Number.isFinite(m)) return "";
  const d = new Date();
  d.setHours(h, m, 0, 0);
  return d.toLocaleTimeString(undefined, { hour: "numeric", minute: "2-digit" });
}

// Day-list ordering for the Home dashboard: tasks with a time come first,
// in time order; untimed tasks sit after them in creation order (never
// interleaved by guesswork — same "an absent value doesn't become 0"
// convention the Dynamics seat-count sort already uses).
export function compareByTimeThenCreated(a: Task, b: Task): number {
  const at = a.time || "";
  const bt = b.time || "";
  if (at && bt) return at.localeCompare(bt) || a.createdAt.localeCompare(b.createdAt);
  if (at) return -1;
  if (bt) return 1;
  return a.createdAt.localeCompare(b.createdAt);
}

export function tasksForDay(tasks: Task[], dayKey: string): Task[] {
  return tasks.filter((t) => t.date === dayKey).sort((a, b) => new Date(a.createdAt).getTime() - new Date(b.createdAt).getTime());
}
